from ui.boxes.BaseBox import BaseBox
from ui.boxes.CanvasDemoBox import CanvasDemoBox
from ui.boxes.ComboBoxDemo import ComboBaseBoxDemo
from ui.boxes.ConsoleBox import ConsoleBaseBox
from ui.boxes.MessageBox import MessageBaseBox
from ui.boxes.ParamBox import ParamBaseBox
from ui.boxes.PlotVzBox import PlotVzBaseBox
from ui.boxes.LogReaderBox import LogReaderBaseBox
from ui.boxes.NodeBox import NodeBaseBox
from ui.boxes.GfxEngine3DBox import GfxEngine3DBox
from ui.boxes.IMUBox import IMUBox