from ui.boxes.BaseBox import BaseBox
from ui.boxes.CanvasDemoBox import CanvasDemoBox
from ui.boxes.ConsoleBox import ConsoleBox
from ui.boxes.InputConsoleBox import InputConsoleBox
from ui.boxes.MessageBox import MessageBox
from ui.boxes.ParamBox import ParamBox
from ui.boxes.PlotVzBox import PlotVzBox
from ui.boxes.LogReaderBox import LogReaderBox
from ui.boxes.NodeBox import NodeBox
from ui.boxes.IMUBox import IMUBox
from ui.boxes.PointsCouldBox import PointsCouldBox
from ui.boxes.FastLioMappingBox import FastLioMappingBox
from ui.boxes.PointsFaceBox import PointsFaceBox