from ui.boxes.BaseBox import BaseBox
from ui.boxes.CanvasDemoBox import CanvasDemoBox
from ui.boxes.ComboBoxDemo import ComboBaseBoxDemo
from ui.boxes.ConsoleBox import ConsoleBaseBox
from ui.boxes.IMU3DBox import IMU3DBox
from ui.boxes.LogReaderBox import LogReaderBaseBox
from ui.boxes.MessageBox import MessageBaseBox
from ui.boxes.NodeBox import NodeBaseBox
from ui.boxes.ParamBox import ParamBaseBox
from ui.boxes.PlotVzBox import PlotVzBaseBox
