# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: imu_info.proto
# Protobuf Python Version: 5.29.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    1,
    '',
    'imu_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eimu_info.proto\x12\tsimulator\"\xe6\x02\n\x07IMUInfo\x12\x33\n\x0borientation\x18\x01 \x01(\x0b\x32\x1e.simulator.IMUInfo.Orientation\x12<\n\x10\x61ngular_velocity\x18\x02 \x01(\x0b\x32\".simulator.IMUInfo.AngularVelocity\x12\x42\n\x13linear_acceleration\x18\x03 \x01(\x0b\x32%.simulator.IMUInfo.LinearAcceleration\x1a\x39\n\x0bOrientation\x12\t\n\x01w\x18\x01 \x01(\x02\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\t\n\x01z\x18\x04 \x01(\x02\x1a\x32\n\x0f\x41ngularVelocity\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x1a\x35\n\x12LinearAcceleration\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'imu_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMUINFO']._serialized_start=30
  _globals['_IMUINFO']._serialized_end=388
  _globals['_IMUINFO_ORIENTATION']._serialized_start=224
  _globals['_IMUINFO_ORIENTATION']._serialized_end=281
  _globals['_IMUINFO_ANGULARVELOCITY']._serialized_start=283
  _globals['_IMUINFO_ANGULARVELOCITY']._serialized_end=333
  _globals['_IMUINFO_LINEARACCELERATION']._serialized_start=335
  _globals['_IMUINFO_LINEARACCELERATION']._serialized_end=388
# @@protoc_insertion_point(module_scope)
